### ISSUE TITLE
Remove version dependency for faraday and rack-oauth2

### ISSUE THREAD

**Issue by msuliq** [nov/openid_connect#100]
Hi,

Would it be possible to remove version ties for the `faraday` and `rack-oauth2` gems in the gemspec file? Right now the gemspec enforces following versions:
```ruby
  s.add_runtime_dependency 'faraday', '~> 2.0'
  s.add_runtime_dependency "rack-oauth2", "~> 2.2"
```
I modified my local copy of `openid_connect` to depend on the latest versions of these 2 gems and it works fine in the scenario of omniauth authentication. Removing versions would help integrating it with Rails applications using more recent versions of `faraday` and `rack-oauth2`

**Comment by nov** [comment]
you can use latest of them already.
