### ISSUE TITLE
Migration from openid_connect 1.1.8 to 2.3.0: where is the httpclient of OpenIDConnect::AccessToken?

### ISSUE THREAD

**Issue by fwolff** [nov/openid_connect#102]
Hello,

I'm migrating from openid_connect 1.1.8 to 2.3.0 and I used to get an authenticated httpclient this way:

```ruby
access_token = OpenIDConnect::AccessToken.new(
      access_token: session[:access_token],
      client: client # OpenIDConnect::Client instance
)
access_token.httpclient
```

The [`httpclient`](https://github.com/nov/rack-oauth2/blob/70da234801c53a116c2d8e126bb09f237824af5a/lib/rack/oauth2/access_token.rb#L21) is gone and I couldn't find any equivalent so far.

Could you tell me how to get or build this http client?

Tanks.

**Comment by nov** [comment]
it's here.
https://github.com/nov/rack-oauth2/blob/70da234801c53a116c2d8e126bb09f237824af5a/lib/rack/oauth2/access_token.rb#L21C11-L25
