### ISSUE TITLE
Access to ErrorWithConnectExt in Rack::OAuth2::Server::Authorize::Code::Request

### ISSUE THREAD

**Issue by patrickatroli** [nov/openid_connect#20]
If an OpenID Connect Client sets the "prompt=none" in their params when contacting the OP's authorization endpoint, if the user isn't logged into the OP, the OP should respond with

    HTTP/1.1 302 Found
    Location: https://client.example.org/cb?
    error=login_required
    &error_description=
      End%20User%20authentication%20required
    &state=af0ifjsldkj

right?

It'd be super useful if in the `Rack::OAuth2::Server::Authorize.new do | req, res |` block, you could call `req.login_required!` in the same way you can call `req.access_denied!` etc, because that's the appropriate place for validating this sort of logic (I think). But `ErrorWithConnectExt` is only included in Rack::OAuth2::Server::Authorize::Request, while `req` appears to be a `Rack::OAuth2::Server::Authorize::Code::Request`

**Comment by nov** [comment]
Can't you call it??
The ext module should be included in rack-oauth2 auth req classes, I think.

**Comment by patrickatroli** [comment]
I'm probably being stupid here, but if I use your unmodified [sample provider](https://github.com/nov/openid_connect_sample),  in [AuthorizationEndpoint](https://github.com/nov/openid_connect_sample/blob/master/lib/authorization_endpoint.rb) in the `Rack::OAuth2::Server::Authorize.new do |req, res|` block, if I try to call `req.login_required!` I get back:

    NoMethodError Exception: undefined method `login_required!' for 
    #<Rack::OAuth2::Server::Authorize::Code::Request:0x007f34e0ccb610>

But I can call `req.invalid_request!` and all the other errors defined in your [rack-oauth2 errors](https://github.com/nov/rack-oauth2/blob/06bec89881f6bd2b5470459de5364b24ab61f14d/lib/rack/oauth2/server/authorize/error.rb).

**Comment by nov** [comment]
That's why you aren't requiring the ext module?

**Comment by patrickatroli** [comment]
Ok, I'm being really n00bish here: How can I require the ext module, and where should I do it?

If I try `req.class.send :include, Rack::OAuth2::Server::Authorize::ErrorWithConnectExt` from inside `Rack::OAuth2::Server::Authorize.new do |req, res|`

I get

     uninitialized constant Rack::OAuth2::Server::Authorize::ErrorWithConnectExt

**Comment by nov** [comment]
You can require it like this, whenever you initialize your app.
In Rails, `config/initializers/openid_connect.rb` etc.
```ruby
require 'rack/oauth2/server/authorize/error_with_connect_ext.rb'
```

**Comment by patrickatroli** [comment]
Oh of course, that's working perfectly now. Thanks Nov, you're the king!

**Comment by nov** [comment]
Since it's not testes well, the behavior can change in future commits.
Please be aware when you update openid_connect gem.

ps.
When I tested the ext module enough, I'll require it as default.
