### ISSUE TITLE
Self signed cert causing 301 too many redirects

### ISSUE THREAD

**Issue by jpete7683** [nov/openid_connect#27]
I am using openid_connect for both my Provider and RP.  On the provider side I have setup nginx with pow, using at the moment a self-sign certificate and during discovery from the client side (also using openid_connect gem) not using any certificate it just goes into a redirect loop because the provider is using force_ssl = true and the openid_connect gem doesn't seem to handle the redirect correctly.  Is this something that can be changed in the code or how would you proceed?

**Comment by nov** [comment]
this gem is just using httpclient gem.
it should follow redirect correctly

**Comment by jpete7683** [comment]
Can you please comment on how you are implementing SSL with the heroku deployment?

**Comment by nov** [comment]
Just doing force_ssl=true

**Comment by jpete7683** [comment]
I cannot even get your examples to run locally with using force_ssl = true, I just get too many redirect loops.  Is there any way you can update the provider portion of the wiki so that I can bypass this discovery that seems to be causing all of my issues?  The IDP we are creating would be nice to just add defined systems to the API with a key/secret/etc.. and specify the IDP just like the following:

Provider.create! [{
  name:                   'Microsoft',
  issuer:                 'https://sts.windows.net/b4ea3de6-839e-4ad1-ae78-c78e5c0cdc06/',
  identifier:             '7db0f079-8e21-4914-9a9b-0896c80f4816',
  secret:                 'Mp8EAXSOlVOeQaAlAADwtboofkUd8gycok8TvTGmKHM=',
  scopes_supported:       [:openid, :profile, :email],
  authorization_endpoint: 'https://login.windows.net/b4ea3de6-839e-4ad1-ae78-c78e5c0cdc06/oauth2/authorize',
  token_endpoint:         'https://login.windows.net/b4ea3de6-839e-4ad1-ae78-c78e5c0cdc06/oauth2/token',
  userinfo_endpoint:      'https://login.windows.net/b4ea3de6-839e-4ad1-ae78-c78e5c0cdc06/openid/userinfo',
  jwks_uri:               'https://login.windows.net/common/discovery/keys'
}, {
  name:                   'mixi',
  issuer:                 'https://mixi.jp',
  identifier:             'd7573a9ad2a9d6a41ebc',
  secret:                 '199c0c8e204227343d36d50100b601c9c1651184',
  scopes_supported:       [:openid, :profile],
  authorization_endpoint: 'https://mixi.jp/connect_authorize.pl',
  token_endpoint:         'https://secure.mixi-platform.com/2/token',
  userinfo_endpoint:      'https://api.mixi-platform.com/2/openid/userinfo'
}]

**Comment by nov** [comment]
you can just remove discovery endpoints from your app...

**Comment by jpete7683** [comment]
I get that I can just remove the endpoints, but how do I on the provider side hard code and serve up the IDP identifier/secret/etc...

**Comment by jpete7683** [comment]
I ended up figuring out the issue.  It doesn't have to do with the fact that I am using a self signed certificate.  I wrote a test app and saw the failure, ended up editing some of the code involved to tell it to ignore verification of the cert and your gem works fine.  You might want to expose the httpclient debugging and potentially allow us to pass options to that gem.  Obviously, I should be using a signed cert but for testing at the moment it would be nice to disable verification so I can prove that the code is working correctly.  Thanks for everything, your gem and examples have gone a long way.

**Comment by nov** [comment]
self-signed certificate shouldn't cause redirect loop.
only redirect response should cause the gem do redirect.

```ruby
pry(main)> OpenIDConnect::Discovery::Provider.discover! "self-signed.com"
OpenSSL::SSL::SSLError: hostname "self-signed.com" does not match the server certificate
from /Users/nov.matake/.rbenv/versions/2.3.0/lib/ruby/2.3.0/openssl/ssl.rb:315:in `post_connection_check'
```

**Comment by jpete7683** [comment]
That is exactly what I am saying.  Basically, I used both your OP and RP examples and built a working IDP and was testing it with the RP example.  Below you can see the error I am getting by using the self signed certificate on the IDP side.

2.2.1 :001 > require 'openid_connect'
 => true 
2.2.1 :002 > OpenIDConnect::Discovery::Provider.discover! "localhost:443"
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:46:in `connect'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:46:in `ssl_connect'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:24:in `create_socket'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:739:in `block in connect'
	from /Users/jarodpeters/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/jarodpeters/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/jarodpeters/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:735:in `connect'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:497:in `query'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient/session.rb:170:in `query'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:1238:in `do_get_block'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:1100:in `follow_redirect'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.1/lib/httpclient.rb:651:in `get_content'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/webfinger-1.0.1/lib/webfinger/request.rb:13:in `block in discover!'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/webfinger-1.0.1/lib/webfinger/request.rb:53:in `handle_response'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/webfinger-1.0.1/lib/webfinger/request.rb:12:in `discover!'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/webfinger-1.0.1/lib/webfinger.rb:15:in `discover!'
	from /Users/jarodpeters/.rvm/gems/ruby-2.2.1/gems/openid_connect-0.9.2/lib/openid_connect/discovery/provider.rb:21:in `discover!'
	from (irb):2
	from /Users/jarodpeters/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'2.2.1
