### ISSUE TITLE
can we drop swd from dependency?

### ISSUE THREAD

**Issue by pravi** [nov/openid_connect#28]
From https://github.com/nov/swd,

NOTE: SWD was designed to be the core of OpenID Connect Discovery, but it's replaced with WebFinger. So I'm no longer supporting this gem.

**Comment by nov** [comment]
Actually, SWD is used for OP Config discovery.
So I'm not supporting SWD gem as a public gem, but using it only for this gem.

**Comment by pravi** [comment]
@nov thanks for the clarification.
