### ISSUE TITLE
puma application leaks socket

### ISSUE THREAD

**Issue by yamamoto-shigeru** [nov/openid_connect#29]
Rails Application with Puma leaks socket when using ominiauth-openid-connect.

It is caused by calling OpenIDConnect.http_client().

OpenIDConnect.http_client calls HTTPClient.new() at,
- https://github.com/nov/openid_connect/blob/master/lib/openid_connect.rb#L66

OpenIDConnect.http_client create new HTTPClient instance.
- https://github.com/nov/openid_connect/blob/master/lib/openid_connect/request_object.rb#L26

get_content() gets data from HTTP Server and keep socket to session_manager without close.

Puma is thread based program and rails applicatoin does not exit.

So, it's cause leak socket.

I think HTTPClient instance is kept at Class variable, and reuse it at calling OpenIDConnect.http_client.

```
  def self.http_client
    if @@http_client
      _http_client_ = @@http_client
    else
      _http_client_ = HTTPClient.new(
        agent_name: "OpenIDConnect (#{VERSION})"
      )
      _http_client_.request_filter << Debugger::RequestFilter.new if debugging?
      http_config.try(:call, _http_client_)
      @@http_client = _http_client_
    end
    _http_client_
  end
```

**Comment by nov** [comment]
Since `OpenIDConnect.http_config` can change over time or per context, I don't think caching `OpenIDConnect.http_client` is good idea.

**Comment by yamamoto-shigeru** [comment]
A socket in a session of HTTPClient is managed by SessionManager.
A socket is kept without closed in a sesion pool of SessionManager, because "persistent connection" is default at HTTP/1.1.

When a socket is closed?
A socket is closed at calling "query()", "reset()" or "reset_all()" of SessionManager.
If a client side does not close a socket, a server side close a socket.
It creates "CLOSE_WAIT" socket at client side.

OpenIDConnect.http_client.get_content() is create new HTTPClient/SessionManager instance.
But there is no time to call "query()", "reset()", or "reset_all()" of created HTTPClient/SessionManager instance.
It cause "CLOSE_WAIT" socket problem.


HTTPClient.new () create new session manager.
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L441

OpenIDConnect.http_client.get_content() gets new session from session manager.
- https://github.com/nov/openid_connect/blob/master/lib/openid_connect/request_object.rb#L26
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L653
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L1102
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L1017
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L1240
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L172


A session is kept by session manager without closing socket.
- https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L1255
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L193
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L296

A socket is closed by calling scrub_cached_session().
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L283

scrub_cached_session() is only called by get_cached_session().
-  https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L263

get_cached_session() is called by get_session() and close().
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L207
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L248

get_session() is only called by query().
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L172

close() is called by reset() and reset_all().
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L184
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L188

**Comment by nov** [comment]
Aren't those sessions closed after @keep_alive_timeout ?

**Comment by yamamoto-shigeru** [comment]
Answer for your question is 'YES' without calling 'query()', 'reset()' or 'reset_all()'.

@keep_alive_timeout is used for session expire process of SessionManager.
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L262
- https://github.com/nahi/httpclient/blob/master/lib/httpclient/session.rb#L291

Session expire process only works at calling 'query()', 'reset()' or 'reset_all()'.

**Comment by nov** [comment]
This calls `Session#close`.
So I assume you are missing something.

```ruby
require 'openid_connect'

class HTTPClient
  class Session
    def close
      puts "Session#close"
      if !@socket.nil? and !@socket.closed?
        # @socket.flush may block when it the socket is already closed by
        # foreign host and the client runs under MT-condition.
        @socket.close
      end
      @state = :INIT
    end
  end
end

http_client = OpenIDConnect.http_client
http_client.get('http://matake.jp')
sleep 15
http_client.get('http://matake.jp')
sleep 15
http_client.get('http://matake.jp')
```

**Comment by nov** [comment]
ah, now understood.
next http call never happens.

however, aren't httpclient instances cleared by GC?

**Comment by yamamoto-shigeru** [comment]
I'm not check GC work at this case.

Generally, IO Class, which is a parent of TCPSocket class, sets 'autoclose' to 'true'.
At GC working, IO Class object closes file descriptor if 'autoclose' is 'true'.
So, I think a half-closed socket will be closed at GC working time.

I find a page,
- [Using HttpClient properly to avoid CLOSE_WAIT TCP connections](https://www.nuxeo.com/blog/using-
httpclient-properly-avoid-closewait-tcp-connections/)

This page says,
```
So what happens then is that when the HttpClient instance goes out of scope it becomes available to the GC, but it will not be garbage collected immediately. Until the GC collects it, the socket connection held internally will stay open and the socket will be stuck in the CLOSE_WAIT state.
```
