### ISSUE TITLE
How to validate access token?

### ISSUE THREAD

**Issue by jtara** [nov/openid_connect#42]
Sorry to post what really is a support question as an Issue. But I am getting desperate trying to understand with the limited documentation. And, unfortunately, rack-oauth2 and json-jwt are equally light on documentation. :(

I validate ID tokens with, e.g.

``` ruby
   id_token = OpenIDConnect::ResponseObject::IdToken.decode id_token_b64,public_keys 
```

I have followed the code, and I see decode checks the signature and will throw *JSON::JWS::VerificationFailed* if the signature does not match. (And I tested it by changing the signature.)

I cannot for the life of me figure out to validate the access token, though. In fact, I had to resort to using the JWT gem (not json-jwt) to decode the access token for debugging.

What am I missing here?

This really needs to be in the documentation. I can't be the only one who doesn't get it.

**Comment by jtara** [comment]
I wound up using:

``` ruby
        decoded_access_token = JSON::JWT.decode access_token.to_s,public_keys
```

Some example in the documentation would save others a lot of grief. openid_connect, rack-oauth2, and json-jwt are a lot to absorb, and understanding the top level requires digging in to the underlying code. A more orthogonal set of methods would help an awful lot.

**Comment by kofronpi** [comment]
@jtara  how do you configure/set public_keys if we use HS256 ? a bit lost with the gem too.. Would like to benefit from your experience ;)

**Comment by jtara** [comment]
@kofronpi, not clear on what your question is, or what (if anything) it has to do specifically with HS256.

Public keys are typically obtained from an endpoint at the provider. 

I download them once, and then in case of a validation error, I refresh the cache.

Maybe this bit of code from a Sinatra app (helpers) will be helpful to you:

``` ruby
    def public_keys
      logger = SemanticLogger['#public_keys']
      if !settings.public_keys
        jwks_uri = "#{ENV['APPID_OAUTH_SERVER_URL']}/publickeys"
        jwks = JSON.parse(
          OpenIDConnect.http_client.get_content(jwks_uri)
        ).with_indifferent_access
        logger.debug 'jwks', jwks
        # uncomment the following two lines to intentionally corrupt the key for test
        #jwks[:keys][0][:n][0] = 'x'
        #logger.debug 'jwks corrupted', jwks
        settings.public_keys = JSON::JWK::Set.new jwks[:keys]
      end
      settings.public_keys
    end

    def get_verified_access_token(client, nonce)
      logger = SemanticLogger['#get_verified_access_token']
      # Note: access_token takes additional parameters to add to token request
      # We need to add the nonce, as openid_connect/rack-oauth2 does not add it
      # Todo: not sure if it really makes sense to re-use the nonce that was created
      # for the authorization request, or use a new one?

      begin
        access_token = client.access_token! nonce: nonce
      rescue Rack::OAuth2::Client::Error => e
        if (e.status == 400 && e.response[:error] == 'invalid_grant') || (e.status == 429)
          logger.warn 'e', e.to_s
        else
          logger.error 'e', e.to_s
        end
        halt e.status, "#{e.status} #{e.to_s}"
      rescue => e
        logger.error 'e', e
        halt 500, "#{e.to_s}"
      end

      decoded_access_token = nil
      logger.debug 'access_token', access_token.to_s if $debug

      2.times do |i|
        begin
          decoded_access_token = JSON::JWT.decode access_token.to_s,public_keys
          # Might raise:
          #  JSON::JWS:VerificationFailed
          #  JSON::JWS::InvalidJSONFormat
          #  JSON::JWS::UnknownAlgorithm
          #  JSON::JWS::UnexpectdAlgorithm
        rescue JSON::JWS::VerificationFailed => e
          settings.public_keys = nil
          logger.warn 'possible public_key rotation', e.inspect
        rescue => e
          logger.error e.inspect
          halt 403, '403 Forbidden'
        else  #success
          break
        end  # begin...rescue...
      end  #2.times

      logger.debug 'decoded_access_token', decoded_access_token

      if !settings.public_keys
        logger.error 'signature mismatch even after refresh public_keys'
        halt 403, '403 Forbidden'
      end
```

**Comment by kofronpi** [comment]
@jtara thank you for your answer, it was helpful :)

**Comment by stanhu** [comment]
https://github.com/nov/openid_connect/issues/61 has more details about making it easier to support HS256.
