### ISSUE TITLE
Wrong claim type "name" after successful authentication

### ISSUE THREAD

**Issue by bjthomson** [nov/openid_connect#43]
I initially raised a documentation issue, then investigated further.
Details here: https://github.com/MicrosoftDocs/azure-docs/issues/18110
tldr; The OpenIDConnect code is adding the users name with a type of **name**, but the ClaimsIdentity property is looking for a type of **http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name**

line 73 in ClaimTypes.cs in the F12 source
public const string Name = ClaimType2005Namespace + "/name";

**Comment by nov** [comment]
why you posted C# issue here?

**Comment by bjthomson** [comment]
I found a bug, searched for "GitHub OpenID Connect" and posted here. Apparently the wrong place.
