### ISSUE TITLE
Don't assume that issuer is a URL

### ISSUE THREAD

**Issue by jtara** [nov/openid_connect#44]
There is an assumption that Issuer is a URL, and no way provided to override.

The OpenID Connect spec does not require that Issuer must be a URL.

I can override issuer matching wtih:

``` ruby
OpenIDConnect.validate_discovery_issuer = false
```

But there is no way provided to override requirement that issuer is a URL.

From *response.rb*:

``` ruby
          uri_attributes = {
            required: [
              :issuer,
              :authorization_endpoint,
              :jwks_uri
            ],
```

``` ruby
          validates *uri_attributes.values.flatten, url: true, allow_nil: true
```

Workaround is to fork and move *:issuer* from *uri_attributes* to *attr_required*. Or do some nasty monkey-patching.

There should be an easy way to override this validation.

An example of a a use case where issuer is not a URL is IBM Cloud (ex-Bluemix) App ID.

Request:

Note I substituted *<tenant uuid>* for real tenant uuid below.

```
https://appid-oauth.ng.bluemix.net/oauth/v3/<tenant uuid>/.well-known/openid-configuration
```

``` json
{
  "issuer": "appid-oauth.ng.bluemix.net",
  "authorization_endpoint": "https://appid-oauth.ng.bluemix.net/oauth/v3/<tenant uuid>/authorization",
  "token_endpoint": "https://appid-oauth.ng.bluemix.net/oauth/v3/<tenant uuid>/token",
  "jwks_uri": "https://appid-oauth.ng.bluemix.net/oauth/v3/<tenant uuid>/publickeys",
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "userinfo_endpoint": "https://appid-oauth.ng.bluemix.net/oauth/v3/<tenant uuid>/userinfo",
  "scopes_supported": [
    "openid"
  ],
  "response_types_supported": [
    "code"
  ],
  "claims_supported": [
    "iss",
    "aud",
    "exp",
    "tenant",
    "iat",
    "sub",
    "nonce",
    "amr",
    "oauth_client"
  ],
  "grant_types_supported": [
    "authorization_code",
    "password",
    "refresh_token",
    "client_credentials",
    "urn:ietf:params:oauth:grant-type:jwt-bearer"
  ],
  "profiles_endpoint": "https://appid-profiles.ng.bluemix.net",
  "service_documentation": "https://console.bluemix.net/docs/services/appid/index.html"
}
```

As well, it would be useful to be able to set the expected issuer for cases where it is not a URL, so that we CAN validate the issuer is as expected.

The problem is I need to include the tenant ID as part of the configuration endpoint. But the returned issuer is:

- not a URL
- and doesn't include the tenant ID

Which is still a valid response.

I don't mind writing a PR, but would like some guidance as to how you would prefer to approach this.

**Comment by nov** [comment]
Issuer MUST be an https url.

**Comment by jtara** [comment]
FWIW, IBM fixed the nonconformance in AppID API v4.

https://www.ibm.com/blogs/bluemix/2019/04/ibm-cloud-app-id-v4-runtime-apis-update/

```
The issuer is now a full URL with a protocol and points to your specific App ID instance in the “cloud.ibm.com” domain.
The audience field is now formatted as an array.
Tokens now have a version. This can be found in the header of the tokens in the ver field.
The gender field has been removed from the identity token. If the field is needed for your apps, you can add it to your token through custom claims mapping.
The OAuth client field has been removed from the access token.
```
