### ISSUE TITLE
Handling providers with alternate discovery issuer urls

### ISSUE THREAD

**Issue by Adverbly** [nov/openid_connect#45]
Warning: Novice alert. Just learned what openid connect was today so sorry if I'm missing something. 

I am using [a gem that wraps this gem using omniauth](https://github.com/m0n9oose/omniauth_openid_connect) in an attempt to use [intuit's openid connect service](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect). I'm having trouble starting out with this because I believe that intuit may be breaking the discovery spec by using different paths for `/.well-known/openid-configuration`.

![image](https://user-images.githubusercontent.com/2197957/59941433-2febd500-942b-11e9-9154-9d2075e7d904.png)

I'm wondering if 

1) There is an existing supported means of overriding the issuer [well known path](https://github.com/nov/openid_connect/blob/007d35f249b028a43391550153c22e9cf006e661/lib/openid_connect/discovery/provider/config/resource.rb#L13)
2) Whether or not what intuit is doing here is off-spec. If it is off-spec, then should perhaps try and bring it up with them. If it is not off-spec, then perhaps this is actually an issue with this library?

**Comment by nov** [comment]
1. no
2. its off-spec

I guess you can add static config option to omniauth-openid_connect, so than it won’t access discovery doc.

**Comment by WestFarmer** [comment]
Inside kubernetes cluster, the discovery endpoint is usually have different host:port than front url.

please make this a config option, more flexible to support more real world use cases.

**Comment by kylekyle** [comment]
You can bypass discover validation: 

```ruby
  discover = OpenIDConnect::Discovery::Provider::Config::Resource.new(
    URI('YOUR PROVIDER HERE')
  ).discover!
```
