### ISSUE TITLE
how to test the discovery endpoint via HTTP in my dev environment ?

### ISSUE THREAD

**Issue by lixiran** [nov/openid_connect#49]
I am working on gitlab and keycloak integration via openid connect.
I am just doing some prototype. so http is quite enough.
I only have self-signed cert on my dev envs. but it cause many problem. like:
OpenIDConnect::Discovery::DiscoveryFailed (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate))
OpenIDConnect::Discovery::DiscoveryFailed (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)):

our production has official cert but my dev env don't. so I just want to demo the the integration in via http.

**Comment by nov** [comment]
You can easily use https on your local using puma-dev. Otherwise, you need to go complex way.

**Comment by lixiran** [comment]
what is the "complex way" ?
I can try puma-dev. on the other hand, if puma doesn't work. I can try the complex way

**Comment by nov** [comment]
monkey patching

**Comment by lixiran** [comment]
aha... heard of that... 
ok. I may try puma-dev first..
I need to install both gitlab and keycloak on puma ?

**Comment by CrowdHailer** [comment]
I also ran into this problem. It would be really useful for test.
Would you be interested in supporting http on localhost only?

**Comment by nov** [comment]
I don't have plan to support http here.
