### ISSUE TITLE
Can/should IAT be optional

### ISSUE THREAD

**Issue by cocogorilla** [nov/openid_connect#51]
When I validate my tokens, I'm receiving failure that "iat is required".  This appears to be the case from spec.  However, its optional I believe in the RFC?

4.1.6.  "iat" (Issued At) Claim

   The "iat" (issued at) claim identifies the time at which the JWT was
   issued.  This claim can be used to determine the age of the JWT.  Its
   value MUST be a number containing a NumericDate value.  Use of this
   claim is OPTIONAL.

**Comment by nov** [comment]
`iat` is REQUIRED in OpenID Connect ID Token.
