### ISSUE TITLE
cache_key method is not FIPS complaint (using MD5)

### ISSUE THREAD

**Issue by nahumcohen** [nov/openid_connect#52]
### Steps to reproduce
1. Make sure that ruby is running with OpenSSL FIPS complaint version. E.g. [OpenSSL_1_0_2u](https://github.com/openssl/openssl/tree/OpenSSL_1_0_2u/)
2. Enable FIPS mode in your application by adding the following:
```
OpenSSL.fips_mode = true
```
4. Invoke [cache_key](https://github.com/nov/openid_connect/blob/a3ec9145dcb637e420ebbb9b1858bdadfbe3e575/lib/openid_connect/discovery/provider/config/resource.rb#L29) method that using MD5.

### Expected behavior

Perform a valid openid_connect action for our use case.

### Actual behavior

The Fatal low level API exception is thrown
`md5_dgst.c(75): OpenSSL internal error, assertion failed: Low level API call to digest MD5 forbidden in FIPS mode!`

### System configuration
**Ruby version**:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

We are using a workaround overriding cache_key method.
```
# override OpenIDConnect cache_key with FIPS complaint method
OpenIDConnect::Discovery::Provider::Config::Resource.module_eval do
  def cache_key
    sha256 = Digest::SHA256.hexdigest host
    "swd:resource:opneid-conf:#{sha256}"
  end
end
```
This is obviously not the correct solution. We can open a pull request and work together to find the right one.

**Comment by nov** [comment]
Hi, thanks for your reporting.
I'm welcome to your PR.
