### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) 

### ISSUE THREAD

**Issue by diegosteiner** [nov/openid_connect#63]
An OpenIDConnect::Discovery::DiscoveryFailed exception is being raised when trying to discover an endpoint that has en Let's encrypt certificate. 

Problem is the httpclient dependency, which uses outdated root certificates: https://github.com/nahi/httpclient/issues/445

**Comment by nov** [comment]
Hi, I've just released a fix with v1.3.0
