### ISSUE TITLE
OpenID Connect Federation

### ISSUE THREAD

**Issue by MdreW** [nov/openid_connect#64]
Hi all,

I would like to implement the [openid connect federation protocol](https://openid.net/specs/openid-connect-federation-1_0-ID3.html) in a project of mine but at the moment the library does not support it.

Are you planning or interested to add this feature?
I don't have huge skills but, if you aren't already, can I give it a try?

P.S. apologize for my poor english :sweat_smile:

**Comment by nov** [comment]
Hi, I'm not following OIDC federation spec right now, but I'm welcome if you can try.
