### ISSUE TITLE
Emails not going through

### ISSUE THREAD

**Issue by arif-muhammad-wmc-tech** [nov/openid_connect#81]
Installed openid_connect in an app having ruby '2.2.3' and rails '4.1.5'.

Existing email functionality has stopped working, none of the emails are going through without any exceptions. Tried but not able to figure out the issue.

In the Gemfile.lock the existing mail version is ~> 2.5.4

    actionmailer (4.1.5)
      actionpack (= 4.1.5)
      actionview (= 4.1.5)
      **mail (~> 2.5.4)**

Open id connect installs a dependency validate_email which uses mail 

    validate_email (0.1.6)
      activemodel (>= 3.0)
      **mail (>= 2.2.5)**

Any workaround on this?

**Comment by nov** [comment]
I don't get what's the problem.
