### ISSUE TITLE
Cache jwks_uri response

### ISSUE THREAD

**Issue by edgurgel3p** [nov/openid_connect#87]
Hi @nov, 

First I would like to thank you for maintaining this great library.

I'm using [omniauth_openid_connect](https://github.com/omniauth/omniauth_openid_connect) and it seems to always fetch the keys from the `jwks_uri`. 

https://github.com/omniauth/omniauth_openid_connect/blob/b4965d09f0ec096517d25a7e7a1e23ebc57172f7/lib/omniauth/strategies/openid_connect.rb#L204-L206

I can see that the config.jwks is [memoised](https://github.com/nov/openid_connect/blob/master/lib/openid_connect/discovery/provider/config/response.rb#L83-L86) and that there is already a cache if `config.jwk(kid)` is used but `omniauth_openid_connect` simply uses the result of the `jwks_uri`.

Given that there is a cache for the config itself and for the individual jwk when using kid would you open for a change to also cache the `jwks_uri` response? If accepted would you have any hints on how to achieve this? `SWD` and `JSON::JWK::Set::Fetcher` have their own cache stores but they don't seem to fit the bill here 🤔. 

I considered opening an issue on `omniauth_openid_connect` to use `config.jwk(kid)` but AFAIK `kid` is an optional/hint field so systems might not provide it and the usual fallback approach is trying to find a key with the specified `alg`.

Another option is to introduce a cache on `omniauth_openid_connect` for the `config.jwks` piece 🤔 

Thanks in advance

**Comment by nov** [comment]
`JSON::JWK::Set::Fetcher` can be used for it too.

**Comment by nov** [comment]
Caching by `kid` is intended behaviour, and I'm not willing to remove `kid` requirement here.
