### ISSUE TITLE
Cannot connect to localhost

### ISSUE THREAD

**Issue by yovasx2** [nov/openid_connect#89]
Hi, I have an oidc server in my local but the lib cannot connect to it using localhost, it gives me an SSL error, i think it is because it's using http and not https

**Comment by ursm** [comment]
I faced the same problem. The following snippet made it work as expected.

``` ruby
# config/initializers/swd.rb

SWD.url_builder = URI::HTTP if Rails.env.local?
```

Hope this helps.

**Comment by northerner** [comment]
Thanks @ursm for putting me on the right path debugging this. In the end I also needed the following to get my local (non-SSL) setup working:

`WebFinger.url_builder = URI::HTTP if Rails.env.local?`
